In [1]:
import pandas as pd

df = pd.read_csv('../data/raw/layoffs.csv')
df.head(10)

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
0,Patreon,SF Bay Area,93.0,7/23/2026,0.2,Media,https://techcrunch.com/2026/07/23/patreon-lays...,Series F,413.0,United States,7/24/2026
1,Amazon,Port St. Lucie,1110.0,7/22/2026,NaN,Retail,https://www.msn.com/en-us/money/companies/amaz...,Post-IPO,8100.0,United States,7/24/2026
2,Monday.com,"Tel Aviv, Non-U.S.",630.0,7/22/2026,0.2,Product,https://techcrunch.com/2026/07/22/monday-com-l...,Post-IPO,384.0,Israel,7/23/2026
3,Amazon,Seattle,NaN,7/22/2026,NaN,Retail,https://www.reuters.com/business/world-at-work...,Post-IPO,8100.0,United States,7/24/2026
4,Uber,SF Bay Area,NaN,7/22/2026,NaN,Transportation,https://www.bloomberg.com/news/articles/2026-0...,Post-IPO,25200.0,United States,7/24/2026
5,Intel,Sacramento,NaN,7/20/2026,NaN,Hardware,https://www.oregonlive.com/silicon-forest/2026...,Post-IPO,12.0,United States,7/22/2026
6,Samsung,New York City,739.0,7/19/2026,NaN,Hardware,https://www.cnbc.com/2026/07/19/samsung-cuts-u...,Post-IPO,NaN,United States,7/22/2026
7,Samsung,Dallas,100.0,7/19/2026,NaN,Hardware,https://www.cnbc.com/2026/07/19/samsung-cuts-u...,Post-IPO,NaN,United States,7/22/2026
8,Polygon,"Cayman Islands, Non-U.S.",NaN,7/16/2026,NaN,Crypto,https://www.thestreet.com/crypto/markets/polyg...,Unknown,451.0,Cayman Islands,7/20/2026
9,Sprout Social,Chicago,260.0,7/15/2026,0.2,Marketing,https://www.marketwatch.com/story/sprout-socia...,Post-IPO,111.0,United States,7/15/2026

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4523 entries, 0 to 4522
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   company              4523 non-null   str
 1   location             4522 non-null   str
 2   total_laid_off       2960 non-null   float64
 3   date                 4523 non-null   str
 4   percentage_laid_off  2833 non-null   float64
 5   industry             4521 non-null   str
 6   source               4520 non-null   str
 7   stage                4516 non-null   str
 8   funds_raised         3990 non-null   float64
 9   country              4521 non-null   str
 10  date_added           4523 non-null   str
dtypes: float64(3), str(8)
memory usage: 388.8 KB

In [3]:
df.describe(include='all')

,company,location,total_laid_off,date,percentage_laid_off,industry,source,stage,funds_raised,country,date_added
count,4523,4522,2960.000000,4523,2833.000000,4521,4520,4516,3990.000000,4521,4523
unique,2952,272,NaN,1275,NaN,30,4262,16,NaN,66,1073
top,Amazon,SF Bay Area,NaN,4/2/2020,NaN,Finance,Internal memo,Post-IPO,NaN,United States,11/17/2022
freq,22,1118,NaN,27,NaN,539,105,1087,NaN,2844,45
mean,NaN,NaN,313.291892,NaN,0.292699,NaN,NaN,NaN,876.629097,NaN,NaN
std,NaN,NaN,1122.910185,NaN,0.303066,NaN,NaN,NaN,4565.499061,NaN,NaN
min,NaN,NaN,3.000000,NaN,0.000000,NaN,NaN,NaN,0.700000,NaN,NaN
25%,NaN,NaN,40.000000,NaN,0.100000,NaN,NaN,NaN,55.000000,NaN,NaN
50%,NaN,NaN,90.000000,NaN,0.170000,NaN,NaN,NaN,175.000000,NaN,NaN
75%,NaN,NaN,200.000000,NaN,0.330000,NaN,NaN,NaN,484.000000,NaN,NaN
max,NaN,NaN,22000.000000,NaN,1.000000,NaN,NaN,NaN,121900.000000,NaN,NaN

In [4]:
df.isnull().sum()

company                   0
location                  1
total_laid_off         1563
date                      0
percentage_laid_off    1690
industry                  2
source                    3
stage                     7
funds_raised            533
country                   2
date_added                0
dtype: int64

In [5]:
df.shape

(4523, 11)

In [ ]:
df['industry'].unique()

<StringArray>
[         'Media',         'Retail',        'Product', 'Transportation',
       'Hardware',         'Crypto',      'Marketing',           'Data',
        'Finance',       'Security',       'Consumer',         'Travel',
          'Legal',          'Other',      'Education',     'Healthcare',
             'HR',     'Recruiting',        'Support',    'Real Estate',
             'AI',           'Food',          'Sales',  'Manufacturing',
      'Logistics', 'Infrastructure',        'Fitness',         'Energy',
              nan,      'Aerospace',   'Construction']
Length: 31, dtype: str

In [8]:
df['stage'].unique()

<StringArray>
[      'Series F',       'Post-IPO',        'Unknown',       'Series G',
           'Seed',       'Acquired',       'Series D',       'Series B',
       'Series C', 'Private Equity',       'Series A',     'Subsidiary',
       'Series E',              nan,       'Series H',       'Series J',
       'Series I']
Length: 17, dtype: str

In [9]:
df['country'].unique()

<StringArray>
[       'United States',               'Israel',       'Cayman Islands',
              'Nigeria',                'India',               'Canada',
          'Netherlands',       'United Kingdom',               'Brazil',
              'Ireland',            'Indonesia',            'Australia',
          'Switzerland',            'Singapore',              'Austria',
              'Germany',              'Denmark',               'Norway',
                'Egypt',               'Sweden', 'United Arab Emirates',
              'Estonia',                'Kenya',               'Cyprus',
          'New Zealand',       'Czech Republic',               'Turkey',
              'Uruguay',                'Japan',             'Portugal',
               'France',                'Malta',                  'UAE',
                'China',             'Pakistan',                'Spain',
              'Belgium',                'Chile',            'Lithuania',
               'Poland',              'Finland',              'Romania',
                    nan,                'Ghana',            'Hong Kong',
           'Luxembourg',               'Mexico',          'South Korea',
         'Saudi Arabia',          'Philippines',              'Ukraine',
                'Italy',             'Colombia',            'Argentina',
           'Seychelles',               'Greece',             'Malaysia',
              'Hungary',              'Vietnam',             'Thailand',
              'Senegal',                 'Peru',              'Bahrain',
               'Russia',             'Bulgaria',         'South Africa',
              'Myanmar']
Length: 67, dtype: str